// Auth hooks
export {
  useAuth,
  useUser,
  useToken,
  usePasswordReset,
  useEmailVerification,
  useMagicLink,
  useOAuth,
  useMFA,
  type UseAuthReturn,
  type UsePasswordResetReturn,
  type UseEmailVerificationReturn,
  type UseMagicLinkReturn,
  type UseOAuthReturn,
  type UseMFAReturn,
} from "./useAuth";

// Query hooks
export {
  useQuery,
  useQueryById,
  useQueryFirst,
  usePaginatedQuery,
  useInfiniteQuery,
  useCount,
  type QueryStatus,
  type UseQueryOptions,
  type UseQueryReturn,
  type UseQueryFirstReturn,
  type UsePaginatedQueryOptions,
  type UsePaginatedQueryReturn,
  type UseInfiniteQueryOptions,
  type UseInfiniteQueryReturn,
} from "./useQuery";

// Mutation hooks
export {
  useMutation,
  useCreate,
  useUpdate,
  useDelete,
  useUpsert,
  useBatchCreate,
  useBatchUpdate,
  useBatchDelete,
  useOptimisticMutation,
  type MutationStatus,
  type UseMutationOptions,
  type UseMutationReturn,
  type UseCreateOptions,
  type UseUpdateOptions,
  type UseDeleteOptions,
  type UseUpsertOptions,
} from "./useMutation";

// Realtime hooks
export {
  useSubscription,
  useChannel,
  usePresence,
  useRealtimeConnection,
  useBroadcast,
  type UseRealtimeOptions,
  type UseSubscriptionOptions,
  type UseSubscriptionReturn,
  type UseChannelOptions,
  type UseChannelReturn,
  type UsePresenceOptions,
  type UsePresenceReturn,
} from "./useRealtime";

// Storage hooks
export {
  useUpload,
  useDownload,
  useFile,
  useFiles,
  useDropzone,
  usePublicUrl,
  type UseUploadOptions,
  type UseUploadReturn,
  type UseDownloadOptions,
  type UseDownloadReturn,
  type UseFileOptions,
  type UseFileReturn,
  type UseFilesOptions,
  type UseFilesReturn,
  type DropzoneOptions,
  type DropzoneState,
  type UseDropzoneReturn,
} from "./useStorage";

// Functions hooks
export {
  useFunction,
  useRpc,
  useFunctionList,
  useBatchInvoke,
  useScheduledFunction,
  type UseFunctionOptions,
  type UseFunctionReturn,
  type UseRpcOptions,
  type UseRpcReturn,
  type UseFunctionListOptions,
  type UseFunctionListReturn,
} from "./useFunctions";

// Observability hooks
export {
  useMetrics,
  useAuditLogs,
  useIncidents,
  useSystemHealth,
  useRealtimeStats,
  useErrorTracking,
  type UseMetricsOptions,
  type UseMetricsReturn,
  type UseAuditLogsOptions,
  type UseAuditLogsReturn,
  type UseIncidentsOptions,
  type UseIncidentsReturn,
  type UseSystemHealthOptions,
  type UseSystemHealthReturn,
  type UseRealtimeStatsOptions,
  type UseRealtimeStatsReturn,
  type UseErrorTrackingOptions,
  type UseErrorTrackingReturn,
} from "./useObservability";

// MongoDB hooks
export {
  useMongoCollection,
  useMongoFind,
  useMongoFindOne,
  useMongoAggregate,
  useMongoInsertOne,
  useMongoInsertMany,
  useMongoUpdateOne,
  useMongoUpdateMany,
  useMongoDeleteOne,
  useMongoDeleteMany,
  useMongoInfiniteFind,
  useMongoCount,
  useMongoDistinct,
  type MongoQueryStatus,
  type UseMongoFindOptions,
  type UseMongoFindReturn,
  type UseMongoFindOneOptions,
  type UseMongoFindOneReturn,
  type UseMongoAggregateOptions,
  type UseMongoAggregateReturn,
  type UseMongoMutationReturn,
  type UseMongoInsertOneVariables,
  type UseMongoInsertManyVariables,
  type UseMongoUpdateOneVariables,
  type UseMongoUpdateManyVariables,
  type UseMongoDeleteOneVariables,
  type UseMongoDeleteManyVariables,
  type UseMongoInfiniteFindOptions,
  type UseMongoInfiniteFindReturn,
  type UseMongoCountOptions,
} from "./useMongoDB";
